// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Advertisement documents
 */
interface AdvertisementDocumentData {
  /**
   * background field in *Advertisement*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: advertisement.background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * content field in *Advertisement*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advertisement.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * CTA Label field in *Advertisement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advertisement.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Advertisement*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advertisement.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Inverted text color field in *Advertisement*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: advertisement.inverted_text_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  inverted_text_color: prismic.BooleanField;
}

/**
 * Advertisement document from Prismic
 *
 * - **API ID**: `advertisement`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AdvertisementDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AdvertisementDocumentData>,
    "advertisement",
    Lang
  >;

/**
 * Content for age documents
 */
interface AgeDocumentData {
  /**
   * name field in *age*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: age.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * value field in *age*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: age.value
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  value: prismic.NumberField;

  /**
   * description field in *age*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: age.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * age document from Prismic
 *
 * - **API ID**: `age`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AgeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AgeDocumentData>, "age", Lang>;

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * image field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

type BlogHomepageDocumentDataSlicesSlice = never;

/**
 * Content for Blog Homepage documents
 */
interface BlogHomepageDocumentData {
  /**
   * title field in *Blog Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Blog Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_homepage.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Slice Zone field in *Blog Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogHomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Homepage document from Prismic
 *
 * - **API ID**: `blog_homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogHomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogHomepageDocumentData>,
    "blog_homepage",
    Lang
  >;

/**
 * Item in *BlogPost → tag*
 */
export interface BlogpostDocumentDataTagItem {
  /**
   * name field in *BlogPost → tag*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.tag[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"tag">;
}

type BlogpostDocumentDataSlicesSlice =
  | ExperienceSlice
  | AdvertisementSlice
  | ListSlice
  | ParagraphSlice;

/**
 * Content for BlogPost documents
 */
interface BlogpostDocumentData {
  /**
   * Title field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *BlogPost*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Image field in *BlogPost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Read time field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.read_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  read_time: prismic.KeyTextField;

  /**
   * Published field in *BlogPost*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  published: prismic.TimestampField;

  /**
   * Author field in *BlogPost*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * tag field in *BlogPost*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.tag[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tag: prismic.GroupField<Simplify<BlogpostDocumentDataTagItem>>;

  /**
   * Slice Zone field in *BlogPost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice> /**
   * Meta Description field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *BlogPost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

/**
 * Item in *category → siblings*
 */
export interface CategoryDocumentDataSiblingsItem {
  /**
   * link field in *category → siblings*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: category.siblings[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<
    "category" | "type" | "view" | "season"
  >;
}

type CategoryDocumentDataSlicesSlice =
  | CategoryGallerySlice
  | CuratedContentSlice
  | AdvertisementSlice;

/**
 * Content for category documents
 */
interface CategoryDocumentData {
  /**
   * title field in *category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * siblings field in *category*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category.siblings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  siblings: prismic.GroupField<Simplify<CategoryDocumentDataSiblingsItem>>;

  /**
   * Promoted Content field in *category*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: category.promoted_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  promoted_content: prismic.ContentRelationshipField<"advertisement">;

  /**
   * image field in *category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"thumbnail">;

  /**
   * Slice Zone field in *category*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: category.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CategoryDocumentDataSlicesSlice> /**
   * Meta Description field in *category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: category.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: category.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *Experience → location*
 */
export interface ExperienceDocumentDataLocationItem {
  /**
   * name field in *Experience → location*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.location[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"location">;
}

/**
 * Item in *Experience → season*
 */
export interface ExperienceDocumentDataSeasonItem {
  /**
   * name field in *Experience → season*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.season[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"season">;
}

/**
 * Item in *Experience → category*
 */
export interface ExperienceDocumentDataCategoryItem {
  /**
   * name field in *Experience → category*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.category[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"category">;
}

/**
 * Item in *Experience → landmark*
 */
export interface ExperienceDocumentDataLandmarkItem {
  /**
   * name field in *Experience → landmark*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.landmark[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"landmark">;
}

/**
 * Item in *Experience → type*
 */
export interface ExperienceDocumentDataTypeItem {
  /**
   * name field in *Experience → type*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.type[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"type">;
}

/**
 * Item in *Experience → age*
 */
export interface ExperienceDocumentDataAgeItem {
  /**
   * name field in *Experience → age*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.age[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"age">;
}

/**
 * Item in *Experience → tag*
 */
export interface ExperienceDocumentDataTagItem {
  /**
   * name field in *Experience → tag*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.tag[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"tag">;
}

/**
 * Item in *Experience → duration*
 */
export interface ExperienceDocumentDataDurationItem {
  /**
   * Hours field in *Experience → duration*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.duration[].hours
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  hours: prismic.NumberField;

  /**
   * Minutes field in *Experience → duration*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.duration[].minutes
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  minutes: prismic.NumberField;
}

/**
 * Item in *Experience → Group size*
 */
export interface ExperienceDocumentDataGroupSizeItem {
  /**
   * name field in *Experience → Group size*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.group_size[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"group_size">;
}

type ExperienceDocumentDataSlicesSlice =
  | LocationSlice
  | InstagramSlice
  | AdvertisementSlice
  | ListSlice
  | ParagraphSlice
  | ImageGallerySlice;

/**
 * Item in *Experience → icons*
 */
export interface ExperienceDocumentDataIconsItem {
  /**
   * svg field in *Experience → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.icons[].svg
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  svg: prismic.KeyTextField;

  /**
   * label field in *Experience → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.icons[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * tooltip field in *Experience → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.icons[].tooltip
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tooltip: prismic.KeyTextField;
}

/**
 * Content for Experience documents
 */
interface ExperienceDocumentData {
  /**
   * Title field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Experience*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * location field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.location[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  location: prismic.GroupField<Simplify<ExperienceDocumentDataLocationItem>>;

  /**
   * GeoPoint field in *Experience*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.geopoint
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  geopoint: prismic.GeoPointField;

  /**
   * bokun id field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.bokun_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bokun_id: prismic.KeyTextField;

  /**
   * season field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.season[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  season: prismic.GroupField<Simplify<ExperienceDocumentDataSeasonItem>>;

  /**
   * category field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.category[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  category: prismic.GroupField<Simplify<ExperienceDocumentDataCategoryItem>>;

  /**
   * landmark field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.landmark[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  landmark: prismic.GroupField<Simplify<ExperienceDocumentDataLandmarkItem>>;

  /**
   * type field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.type[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  type: prismic.GroupField<Simplify<ExperienceDocumentDataTypeItem>>;

  /**
   * age field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.age[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  age: prismic.GroupField<Simplify<ExperienceDocumentDataAgeItem>>;

  /**
   * age disclaimer field in *Experience*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.age_disclaimer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  age_disclaimer: prismic.RichTextField;

  /**
   * Physical Difficulty field in *Experience*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.physical_difficulty
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  physical_difficulty: prismic.SelectField<"Easy" | "Moderate" | "Difficult">;

  /**
   * tag field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.tag[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tag: prismic.GroupField<Simplify<ExperienceDocumentDataTagItem>>;

  /**
   * duration field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.duration[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  duration: prismic.GroupField<Simplify<ExperienceDocumentDataDurationItem>>;

  /**
   * Group size field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.group_size[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_size: prismic.GroupField<Simplify<ExperienceDocumentDataGroupSizeItem>>;

  /**
   * Slice Zone field in *Experience*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExperienceDocumentDataSlicesSlice> /**
   * Meta Description field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: experience.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Experience*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: experience.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * icons field in *Experience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.icons[]
   * - **Tab**: Overview Icons
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  icons: prismic.GroupField<Simplify<ExperienceDocumentDataIconsItem>> /**
   * offer field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.offer
   * - **Tab**: Price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  offer: prismic.KeyTextField;

  /**
   * price field in *Experience*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.price
   * - **Tab**: Price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * disclaimer field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.disclaimer
   * - **Tab**: Price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  disclaimer: prismic.KeyTextField;
}

/**
 * Experience document from Prismic
 *
 * - **API ID**: `experience`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperienceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExperienceDocumentData>,
    "experience",
    Lang
  >;

/**
 * Item in *Footer → Payment Logos*
 */
export interface FooterDocumentDataPaymentLogosItem {
  /**
   * image field in *Footer → Payment Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.payment_logos[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Footer → Member Logos*
 */
export interface FooterDocumentDataMemberLogosItem {
  /**
   * image field in *Footer → Member Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.member_logos[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Footer → Book Links*
 */
export interface FooterDocumentDataBookLinksItem {
  /**
   * label field in *Footer → Book Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.book_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *Footer → Book Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.book_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Footer → Useful Links*
 */
export interface FooterDocumentDataUsefulLinksItem {
  /**
   * label field in *Footer → Useful Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.useful_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *Footer → Useful Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.useful_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Footer → Social Media*
 */
export interface FooterDocumentDataSocialMediaItem {
  /**
   * label field in *Footer → Social Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *Footer → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * icon field in *Footer → Social Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Item in *Footer → CTA*
 */
export interface FooterDocumentDataCtaItem {
  /**
   * label field in *Footer → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *Footer → CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * phone field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * address field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Payment Logos field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.payment_logos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  payment_logos: prismic.GroupField<
    Simplify<FooterDocumentDataPaymentLogosItem>
  >;

  /**
   * Member Logos field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.member_logos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  member_logos: prismic.GroupField<Simplify<FooterDocumentDataMemberLogosItem>>;

  /**
   * Book Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.book_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  book_links: prismic.GroupField<Simplify<FooterDocumentDataBookLinksItem>>;

  /**
   * Useful Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.useful_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  useful_links: prismic.GroupField<Simplify<FooterDocumentDataUsefulLinksItem>>;

  /**
   * Social Media field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<Simplify<FooterDocumentDataSocialMediaItem>>;

  /**
   * CTA field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta: prismic.GroupField<Simplify<FooterDocumentDataCtaItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

/**
 * Content for Group size documents
 */
interface GroupSizeDocumentData {
  /**
   * name field in *Group size*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: group_size.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Group size document from Prismic
 *
 * - **API ID**: `group_size`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GroupSizeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GroupSizeDocumentData>,
    "group_size",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | CategoryGallerySlice
  | AppBlockSlice
  | StepsBlockSlice
  | TriptychSlice
  | ExperienceSearchBlockSlice
  | CuratedContentSlice
  | WelcomeBannerSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Landmark → tag*
 */
export interface LandmarkDocumentDataTagItem {
  /**
   * name field in *Landmark → tag*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: landmark.tag[].name
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  name: prismic.ContentRelationshipField<"tag">;
}

type LandmarkDocumentDataSlicesSlice =
  | TriptychSlice
  | CuratedContentSlice
  | AdvertisementSlice
  | ParagraphSlice;

/**
 * Content for Landmark documents
 */
interface LandmarkDocumentData {
  /**
   * Title field in *Landmark*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landmark.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Landmark*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landmark.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Hero Image field in *Landmark*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landmark.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * location field in *Landmark*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: landmark.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  location: prismic.ContentRelationshipField<"location">;

  /**
   * tag field in *Landmark*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landmark.tag[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tag: prismic.GroupField<Simplify<LandmarkDocumentDataTagItem>>;

  /**
   * Slice Zone field in *Landmark*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landmark.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandmarkDocumentDataSlicesSlice> /**
   * Meta Description field in *Landmark*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landmark.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landmark*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landmark.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landmark*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landmark.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Landmark document from Prismic
 *
 * - **API ID**: `landmark`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandmarkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandmarkDocumentData>,
    "landmark",
    Lang
  >;

/**
 * Item in *location → siblings*
 */
export interface LocationDocumentDataSiblingsItem {
  /**
   * link field in *location → siblings*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: location.siblings[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<
    "category" | "type" | "view" | "season"
  >;
}

type LocationDocumentDataSlicesSlice = CategoryGallerySlice;

/**
 * Content for location documents
 */
interface LocationDocumentData {
  /**
   * title field in *location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *location*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * siblings field in *location*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: location.siblings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  siblings: prismic.GroupField<Simplify<LocationDocumentDataSiblingsItem>>;

  /**
   * image field in *location*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: location.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *location*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: location.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LocationDocumentDataSlicesSlice>;
}

/**
 * location document from Prismic
 *
 * - **API ID**: `location`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LocationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LocationDocumentData>,
    "location",
    Lang
  >;

/**
 * Content for MessageBanner documents
 */
interface MessagebannerDocumentData {
  /**
   * Message field in *MessageBanner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: messagebanner.message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message: prismic.KeyTextField;

  /**
   * link field in *MessageBanner*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: messagebanner.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * display field in *MessageBanner*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: messagebanner.display
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display: prismic.BooleanField;
}

/**
 * MessageBanner document from Prismic
 *
 * - **API ID**: `messagebanner`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MessagebannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MessagebannerDocumentData>,
    "messagebanner",
    Lang
  >;

/**
 * Item in *Navbar → Activities*
 */
export interface NavbarDocumentDataActivitiesItem {
  /**
   * menu_label field in *Navbar → Activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.activities[].menu_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_label: prismic.KeyTextField;

  /**
   * menu_link field in *Navbar → Activities*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.activities[].menu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menu_link: prismic.LinkField;
}

/**
 * Item in *Navbar → Menu Items*
 */
export interface NavbarDocumentDataMenuItemsItem {
  /**
   * Menu Label field in *Navbar → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_items[].menu_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_label: prismic.KeyTextField;

  /**
   * Menu Link field in *Navbar → Menu Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_items[].menu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  menu_link: prismic.LinkField;
}

type NavbarDocumentDataSlicesSlice = never;

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * CTA label field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * logo field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Activities field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.activities[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  activities: prismic.GroupField<Simplify<NavbarDocumentDataActivitiesItem>>;

  /**
   * Menu Items field in *Navbar*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.menu_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_items: prismic.GroupField<Simplify<NavbarDocumentDataMenuItemsItem>>;

  /**
   * Slice Zone field in *Navbar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavbarDocumentDataSlicesSlice>;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NavbarDocumentData>, "navbar", Lang>;

/**
 * Item in *season → siblings*
 */
export interface SeasonDocumentDataSiblingsItem {
  /**
   * link field in *season → siblings*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: season.siblings[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<
    "category" | "type" | "view" | "season"
  >;
}

type SeasonDocumentDataSlicesSlice = CuratedContentSlice | AdvertisementSlice;

/**
 * Content for season documents
 */
interface SeasonDocumentData {
  /**
   * title field in *season*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: season.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *season*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: season.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * siblings field in *season*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: season.siblings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  siblings: prismic.GroupField<Simplify<SeasonDocumentDataSiblingsItem>>;

  /**
   * Promoted Content field in *season*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: season.promoted_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  promoted_content: prismic.ContentRelationshipField<"advertisement">;

  /**
   * Slice Zone field in *season*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: season.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SeasonDocumentDataSlicesSlice> /**
   * Meta Description field in *season*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: season.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *season*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: season.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *season*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: season.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * season document from Prismic
 *
 * - **API ID**: `season`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SeasonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SeasonDocumentData>, "season", Lang>;

/**
 * Content for tag documents
 */
interface TagDocumentData {
  /**
   * name field in *tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tag.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * description field in *tag*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tag.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * badge field in *tag*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tag.badge
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  badge: prismic.BooleanField;
}

/**
 * tag document from Prismic
 *
 * - **API ID**: `tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TagDocumentData>, "tag", Lang>;

/**
 * Item in *type → siblings*
 */
export interface TypeDocumentDataSiblingsItem {
  /**
   * link field in *type → siblings*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: type.siblings[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<
    "category" | "type" | "view" | "season"
  >;
}

type TypeDocumentDataSlicesSlice = CuratedContentSlice | AdvertisementSlice;

/**
 * Content for type documents
 */
interface TypeDocumentData {
  /**
   * title field in *type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: type.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *type*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: type.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * siblings field in *type*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: type.siblings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  siblings: prismic.GroupField<Simplify<TypeDocumentDataSiblingsItem>>;

  /**
   * Promoted Content field in *type*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: type.promoted_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  promoted_content: prismic.ContentRelationshipField<"advertisement">;

  /**
   * Slice Zone field in *type*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: type.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TypeDocumentDataSlicesSlice> /**
   * Meta Description field in *type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: type.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *type*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: type.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: type.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * type document from Prismic
 *
 * - **API ID**: `type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TypeDocumentData>, "type", Lang>;

/**
 * Item in *view → siblings*
 */
export interface ViewDocumentDataSiblingsItem {
  /**
   * link field in *view → siblings*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: view.siblings[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<
    "category" | "type" | "view" | "season"
  >;
}

type ViewDocumentDataSlicesSlice = CuratedContentSlice | AdvertisementSlice;

/**
 * Content for view documents
 */
interface ViewDocumentData {
  /**
   * name field in *view*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: view.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * title field in *view*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: view.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *view*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: view.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * siblings field in *view*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: view.siblings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  siblings: prismic.GroupField<Simplify<ViewDocumentDataSiblingsItem>>;

  /**
   * Promoted Content field in *view*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: view.promoted_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  promoted_content: prismic.ContentRelationshipField<"advertisement">;

  /**
   * Slice Zone field in *view*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: view.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ViewDocumentDataSlicesSlice> /**
   * Meta Description field in *view*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: view.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *view*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: view.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *view*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: view.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * view document from Prismic
 *
 * - **API ID**: `view`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ViewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ViewDocumentData>, "view", Lang>;

export type AllDocumentTypes =
  | AdvertisementDocument
  | AgeDocument
  | AuthorDocument
  | BlogHomepageDocument
  | BlogpostDocument
  | CategoryDocument
  | ExperienceDocument
  | FooterDocument
  | GroupSizeDocument
  | HomepageDocument
  | LandmarkDocument
  | LocationDocument
  | MessagebannerDocument
  | NavbarDocument
  | SeasonDocument
  | TagDocument
  | TypeDocument
  | ViewDocument;

/**
 * Primary content in *Advertisement → Default → Primary*
 */
export interface AdvertisementSliceDefaultPrimary {
  /**
   * advertisement field in *Advertisement → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: advertisement.default.primary.advertisement
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  advertisement: prismic.ContentRelationshipField<"advertisement">;
}

/**
 * Default variation for Advertisement Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvertisementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AdvertisementSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Advertisement → Double → Primary*
 */
export interface AdvertisementSliceDoublePrimary {
  /**
   * Advertisement field in *Advertisement → Double → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: advertisement.double.primary.advertisement
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  advertisement: prismic.ContentRelationshipField<"advertisement">;

  /**
   * Advertisement 2 field in *Advertisement → Double → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: advertisement.double.primary.advertisement2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  advertisement2: prismic.ContentRelationshipField<"advertisement">;
}

/**
 * Double variation for Advertisement Slice
 *
 * - **API ID**: `double`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvertisementSliceDouble = prismic.SharedSliceVariation<
  "double",
  Simplify<AdvertisementSliceDoublePrimary>,
  never
>;

/**
 * Slice variation for *Advertisement*
 */
type AdvertisementSliceVariation =
  | AdvertisementSliceDefault
  | AdvertisementSliceDouble;

/**
 * Advertisement Shared Slice
 *
 * - **API ID**: `advertisement`
 * - **Description**: Advertisement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvertisementSlice = prismic.SharedSlice<
  "advertisement",
  AdvertisementSliceVariation
>;

/**
 * Primary content in *AppBlock → Default → Primary*
 */
export interface AppBlockSliceDefaultPrimary {
  /**
   * title field in *AppBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *AppBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AppBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * App Store link field in *AppBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.default.primary.app_store_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  app_store_link: prismic.LinkField;

  /**
   * Google Play link field in *AppBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.default.primary.google_play_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  google_play_link: prismic.LinkField;

  /**
   * App Store icon field in *AppBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.default.primary.app_store_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  app_store_icon: prismic.ImageField<never>;

  /**
   * Google Play icon field in *AppBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.default.primary.google_play_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  google_play_icon: prismic.ImageField<never>;
}

/**
 * Primary content in *AppBlock → Items*
 */
export interface AppBlockSliceDefaultItem {
  /**
   * Row title field in *AppBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Row svg field in *AppBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.items[].svg
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  svg: prismic.KeyTextField;

  /**
   * Row description field in *AppBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for AppBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AppBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AppBlockSliceDefaultPrimary>,
  Simplify<AppBlockSliceDefaultItem>
>;

/**
 * Slice variation for *AppBlock*
 */
type AppBlockSliceVariation = AppBlockSliceDefault;

/**
 * AppBlock Shared Slice
 *
 * - **API ID**: `app_block`
 * - **Description**: AppBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AppBlockSlice = prismic.SharedSlice<
  "app_block",
  AppBlockSliceVariation
>;

/**
 * Primary content in *CategoryGallery → Default → Primary*
 */
export interface CategoryGallerySliceDefaultPrimary {
  /**
   * title field in *CategoryGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *CategoryGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_gallery.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for CategoryGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoryGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategoryGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CategoryGallery*
 */
type CategoryGallerySliceVariation = CategoryGallerySliceDefault;

/**
 * CategoryGallery Shared Slice
 *
 * - **API ID**: `category_gallery`
 * - **Description**: CategoryGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CategoryGallerySlice = prismic.SharedSlice<
  "category_gallery",
  CategoryGallerySliceVariation
>;

/**
 * Primary content in *CuratedContent → Default → Primary*
 */
export interface CuratedContentSliceDefaultPrimary {
  /**
   * Title field in *CuratedContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curated_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *CuratedContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curated_content.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *CuratedContent → Items*
 */
export interface CuratedContentSliceDefaultItem {
  /**
   * Blog Post field in *CuratedContent → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: curated_content.items[].blog_post
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blog_post: prismic.ContentRelationshipField<"blogpost">;
}

/**
 * Default variation for CuratedContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CuratedContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CuratedContentSliceDefaultPrimary>,
  Simplify<CuratedContentSliceDefaultItem>
>;

/**
 * Slice variation for *CuratedContent*
 */
type CuratedContentSliceVariation = CuratedContentSliceDefault;

/**
 * CuratedContent Shared Slice
 *
 * - **API ID**: `curated_content`
 * - **Description**: CuratedContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CuratedContentSlice = prismic.SharedSlice<
  "curated_content",
  CuratedContentSliceVariation
>;

/**
 * Default variation for Description Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Description*
 */
type DescriptionSliceVariation = DescriptionSliceDefault;

/**
 * Description Shared Slice
 *
 * - **API ID**: `description`
 * - **Description**: Description
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DescriptionSlice = prismic.SharedSlice<
  "description",
  DescriptionSliceVariation
>;

/**
 * Primary content in *Experience → Default → Primary*
 */
export interface ExperienceSliceDefaultPrimary {
  /**
   * experience field in *Experience → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.experience
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  experience: prismic.ContentRelationshipField<"experience">;

  /**
   * Discount code field in *Experience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.default.primary.discount_code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  discount_code: prismic.KeyTextField;
}

/**
 * Default variation for Experience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperienceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Experience*
 */
type ExperienceSliceVariation = ExperienceSliceDefault;

/**
 * Experience Shared Slice
 *
 * - **API ID**: `experience`
 * - **Description**: Experience
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceSlice = prismic.SharedSlice<
  "experience",
  ExperienceSliceVariation
>;

/**
 * Primary content in *ExperienceSearchBlock → Default → Primary*
 */
export interface ExperienceSearchBlockSliceDefaultPrimary {
  /**
   * Title field in *ExperienceSearchBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_search_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *ExperienceSearchBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_search_block.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for ExperienceSearchBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceSearchBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperienceSearchBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ExperienceSearchBlock*
 */
type ExperienceSearchBlockSliceVariation = ExperienceSearchBlockSliceDefault;

/**
 * ExperienceSearchBlock Shared Slice
 *
 * - **API ID**: `experience_search_block`
 * - **Description**: ExperienceSearchBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceSearchBlockSlice = prismic.SharedSlice<
  "experience_search_block",
  ExperienceSearchBlockSliceVariation
>;

/**
 * Primary content in *ImageGallery → Items*
 */
export interface ImageGallerySliceDefaultItem {
  /**
   * image field in *ImageGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageGallerySliceDefaultItem>
>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: ImageGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySlice = prismic.SharedSlice<
  "image_gallery",
  ImageGallerySliceVariation
>;

/**
 * Primary content in *Instagram → Default → Primary*
 */
export interface InstagramSliceDefaultPrimary {
  /**
   * title field in *Instagram → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for Instagram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstagramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InstagramSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Instagram*
 */
type InstagramSliceVariation = InstagramSliceDefault;

/**
 * Instagram Shared Slice
 *
 * - **API ID**: `instagram`
 * - **Description**: Instagram
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstagramSlice = prismic.SharedSlice<
  "instagram",
  InstagramSliceVariation
>;

/**
 * Primary content in *List → Default → Primary*
 */
export interface ListSliceDefaultPrimary {
  /**
   * title field in *List → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * multi column field in *List → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: list.default.primary.multi_column
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  multi_column: prismic.BooleanField;

  /**
   * icon type field in *List → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: regular
   * - **API ID Path**: list.default.primary.icon_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_type: prismic.SelectField<"regular" | "included" | "excluded", "filled">;
}

/**
 * Primary content in *List → Items*
 */
export interface ListSliceDefaultItem {
  /**
   * content field in *List → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for List Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListSliceDefaultPrimary>,
  Simplify<ListSliceDefaultItem>
>;

/**
 * Slice variation for *List*
 */
type ListSliceVariation = ListSliceDefault;

/**
 * List Shared Slice
 *
 * - **API ID**: `list`
 * - **Description**: List
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSlice = prismic.SharedSlice<"list", ListSliceVariation>;

/**
 * Primary content in *Location → Location - Meet → Primary*
 */
export interface LocationSliceDefaultPrimary {
  /**
   * Information field in *Location → Location - Meet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.information
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  information: prismic.RichTextField;

  /**
   * Distance from Reykjavic field in *Location → Location - Meet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.distance_reykjavic
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  distance_reykjavic: prismic.RichTextField;

  /**
   * Start/Pickup GeoPoint field in *Location → Location - Meet → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.start_geopoint
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  start_geopoint: prismic.GeoPointField;

  /**
   * Start/Pickup Info field in *Location → Location - Meet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.start_info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  start_info: prismic.RichTextField;

  /**
   * Start/Pickup Time field in *Location → Location - Meet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.start_time
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  start_time: prismic.RichTextField;

  /**
   * End/Dropoff GeoPoint field in *Location → Location - Meet → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.end_geopoint
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  end_geopoint: prismic.GeoPointField;

  /**
   * End/Dropoff Info field in *Location → Location - Meet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.end_info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  end_info: prismic.RichTextField;

  /**
   * End/Dropoff Time field in *Location → Location - Meet → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.default.primary.end_time
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  end_time: prismic.RichTextField;
}

/**
 * Location - Meet variation for Location Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Location → Location - Pickup Dropoff → Primary*
 */
export interface LocationSliceLocationPickupDropoffPrimary {
  /**
   * Information field in *Location → Location - Pickup Dropoff → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.locationPickupDropoff.primary.information
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  information: prismic.RichTextField;

  /**
   * Distance from Reykjavic field in *Location → Location - Pickup Dropoff → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.locationPickupDropoff.primary.distance_reykjavic
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  distance_reykjavic: prismic.RichTextField;

  /**
   * Start/Pickup GeoPoint field in *Location → Location - Pickup Dropoff → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location.locationPickupDropoff.primary.start_geopoint
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  start_geopoint: prismic.GeoPointField;

  /**
   * Start/Pickup Info field in *Location → Location - Pickup Dropoff → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.locationPickupDropoff.primary.start_info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  start_info: prismic.RichTextField;

  /**
   * Start/Pickup Time field in *Location → Location - Pickup Dropoff → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.locationPickupDropoff.primary.start_time
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  start_time: prismic.RichTextField;

  /**
   * End/Dropoff GeoPoint field in *Location → Location - Pickup Dropoff → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location.locationPickupDropoff.primary.end_geopoint
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  end_geopoint: prismic.GeoPointField;

  /**
   * End/Dropoff Info field in *Location → Location - Pickup Dropoff → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.locationPickupDropoff.primary.end_info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  end_info: prismic.RichTextField;

  /**
   * End/Dropoff Time field in *Location → Location - Pickup Dropoff → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.locationPickupDropoff.primary.end_time
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  end_time: prismic.RichTextField;
}

/**
 * Location - Pickup Dropoff variation for Location Slice
 *
 * - **API ID**: `locationPickupDropoff`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSliceLocationPickupDropoff = prismic.SharedSliceVariation<
  "locationPickupDropoff",
  Simplify<LocationSliceLocationPickupDropoffPrimary>,
  never
>;

/**
 * Slice variation for *Location*
 */
type LocationSliceVariation =
  | LocationSliceDefault
  | LocationSliceLocationPickupDropoff;

/**
 * Location Shared Slice
 *
 * - **API ID**: `location`
 * - **Description**: Location
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSlice = prismic.SharedSlice<
  "location",
  LocationSliceVariation
>;

/**
 * Primary content in *NavLink → Default → Primary*
 */
export interface NavLinkSliceDefaultPrimary {
  /**
   * link field in *NavLink → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_link.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for NavLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavLink*
 */
type NavLinkSliceVariation = NavLinkSliceDefault;

/**
 * NavLink Shared Slice
 *
 * - **API ID**: `nav_link`
 * - **Description**: NavLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavLinkSlice = prismic.SharedSlice<
  "nav_link",
  NavLinkSliceVariation
>;

/**
 * Primary content in *Paragraph → Default → Primary*
 */
export interface ParagraphSliceDefaultPrimary {
  /**
   * title field in *Paragraph → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraph.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Paragraph → Items*
 */
export interface ParagraphSliceDefaultItem {
  /**
   * content field in *Paragraph → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraph.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Paragraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParagraphSliceDefaultPrimary>,
  Simplify<ParagraphSliceDefaultItem>
>;

/**
 * Slice variation for *Paragraph*
 */
type ParagraphSliceVariation = ParagraphSliceDefault;

/**
 * Paragraph Shared Slice
 *
 * - **API ID**: `paragraph`
 * - **Description**: Paragraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParagraphSlice = prismic.SharedSlice<
  "paragraph",
  ParagraphSliceVariation
>;

/**
 * Primary content in *StepsBlock → Default → Primary*
 */
export interface StepsBlockSliceDefaultPrimary {
  /**
   * title field in *StepsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *StepsBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *StepsBlock → Items*
 */
export interface StepsBlockSliceDefaultItem {
  /**
   * Step title field in *StepsBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Step svg field in *StepsBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_block.items[].svg
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  svg: prismic.KeyTextField;

  /**
   * Step description field in *StepsBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for StepsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepsBlockSliceDefaultPrimary>,
  Simplify<StepsBlockSliceDefaultItem>
>;

/**
 * Slice variation for *StepsBlock*
 */
type StepsBlockSliceVariation = StepsBlockSliceDefault;

/**
 * StepsBlock Shared Slice
 *
 * - **API ID**: `steps_block`
 * - **Description**: StepsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepsBlockSlice = prismic.SharedSlice<
  "steps_block",
  StepsBlockSliceVariation
>;

/**
 * Primary content in *Triptych → Items*
 */
export interface TriptychSliceDefaultItem {
  /**
   * link field in *Triptych → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: triptych.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<"landmark">;
}

/**
 * landmarks variation for Triptych Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TriptychSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TriptychSliceDefaultItem>
>;

/**
 * Primary content in *Triptych → Promoted → Primary*
 */
export interface TriptychSlicePromotedPrimary {
  /**
   * title field in *Triptych → Promoted → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: triptych.promoted.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Triptych → Items*
 */
export interface TriptychSlicePromotedItem {
  /**
   * link field in *Triptych → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: triptych.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<"advertisement">;
}

/**
 * Promoted variation for Triptych Slice
 *
 * - **API ID**: `promoted`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TriptychSlicePromoted = prismic.SharedSliceVariation<
  "promoted",
  Simplify<TriptychSlicePromotedPrimary>,
  Simplify<TriptychSlicePromotedItem>
>;

/**
 * Slice variation for *Triptych*
 */
type TriptychSliceVariation = TriptychSliceDefault | TriptychSlicePromoted;

/**
 * Triptych Shared Slice
 *
 * - **API ID**: `triptych`
 * - **Description**: Triptych
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TriptychSlice = prismic.SharedSlice<
  "triptych",
  TriptychSliceVariation
>;

/**
 * Primary content in *WelcomeBanner → Default → Primary*
 */
export interface WelcomeBannerSliceDefaultPrimary {
  /**
   * message field in *WelcomeBanner → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_banner.default.primary.message
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  message: prismic.TitleField;

  /**
   * CTA Name field in *WelcomeBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_banner.default.primary.cta_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_name: prismic.KeyTextField;

  /**
   * CTA link field in *WelcomeBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_banner.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for WelcomeBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WelcomeBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WelcomeBanner*
 */
type WelcomeBannerSliceVariation = WelcomeBannerSliceDefault;

/**
 * WelcomeBanner Shared Slice
 *
 * - **API ID**: `welcome_banner`
 * - **Description**: WelcomeBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeBannerSlice = prismic.SharedSlice<
  "welcome_banner",
  WelcomeBannerSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AdvertisementDocument,
      AdvertisementDocumentData,
      AgeDocument,
      AgeDocumentData,
      AuthorDocument,
      AuthorDocumentData,
      BlogHomepageDocument,
      BlogHomepageDocumentData,
      BlogHomepageDocumentDataSlicesSlice,
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataTagItem,
      BlogpostDocumentDataSlicesSlice,
      CategoryDocument,
      CategoryDocumentData,
      CategoryDocumentDataSiblingsItem,
      CategoryDocumentDataSlicesSlice,
      ExperienceDocument,
      ExperienceDocumentData,
      ExperienceDocumentDataLocationItem,
      ExperienceDocumentDataSeasonItem,
      ExperienceDocumentDataCategoryItem,
      ExperienceDocumentDataLandmarkItem,
      ExperienceDocumentDataTypeItem,
      ExperienceDocumentDataAgeItem,
      ExperienceDocumentDataTagItem,
      ExperienceDocumentDataDurationItem,
      ExperienceDocumentDataGroupSizeItem,
      ExperienceDocumentDataSlicesSlice,
      ExperienceDocumentDataIconsItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataPaymentLogosItem,
      FooterDocumentDataMemberLogosItem,
      FooterDocumentDataBookLinksItem,
      FooterDocumentDataUsefulLinksItem,
      FooterDocumentDataSocialMediaItem,
      FooterDocumentDataCtaItem,
      GroupSizeDocument,
      GroupSizeDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LandmarkDocument,
      LandmarkDocumentData,
      LandmarkDocumentDataTagItem,
      LandmarkDocumentDataSlicesSlice,
      LocationDocument,
      LocationDocumentData,
      LocationDocumentDataSiblingsItem,
      LocationDocumentDataSlicesSlice,
      MessagebannerDocument,
      MessagebannerDocumentData,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataActivitiesItem,
      NavbarDocumentDataMenuItemsItem,
      NavbarDocumentDataSlicesSlice,
      SeasonDocument,
      SeasonDocumentData,
      SeasonDocumentDataSiblingsItem,
      SeasonDocumentDataSlicesSlice,
      TagDocument,
      TagDocumentData,
      TypeDocument,
      TypeDocumentData,
      TypeDocumentDataSiblingsItem,
      TypeDocumentDataSlicesSlice,
      ViewDocument,
      ViewDocumentData,
      ViewDocumentDataSiblingsItem,
      ViewDocumentDataSlicesSlice,
      AllDocumentTypes,
      AdvertisementSlice,
      AdvertisementSliceDefaultPrimary,
      AdvertisementSliceDoublePrimary,
      AdvertisementSliceVariation,
      AdvertisementSliceDefault,
      AdvertisementSliceDouble,
      AppBlockSlice,
      AppBlockSliceDefaultPrimary,
      AppBlockSliceDefaultItem,
      AppBlockSliceVariation,
      AppBlockSliceDefault,
      CategoryGallerySlice,
      CategoryGallerySliceDefaultPrimary,
      CategoryGallerySliceVariation,
      CategoryGallerySliceDefault,
      CuratedContentSlice,
      CuratedContentSliceDefaultPrimary,
      CuratedContentSliceDefaultItem,
      CuratedContentSliceVariation,
      CuratedContentSliceDefault,
      DescriptionSlice,
      DescriptionSliceVariation,
      DescriptionSliceDefault,
      ExperienceSlice,
      ExperienceSliceDefaultPrimary,
      ExperienceSliceVariation,
      ExperienceSliceDefault,
      ExperienceSearchBlockSlice,
      ExperienceSearchBlockSliceDefaultPrimary,
      ExperienceSearchBlockSliceVariation,
      ExperienceSearchBlockSliceDefault,
      ImageGallerySlice,
      ImageGallerySliceDefaultItem,
      ImageGallerySliceVariation,
      ImageGallerySliceDefault,
      InstagramSlice,
      InstagramSliceDefaultPrimary,
      InstagramSliceVariation,
      InstagramSliceDefault,
      ListSlice,
      ListSliceDefaultPrimary,
      ListSliceDefaultItem,
      ListSliceVariation,
      ListSliceDefault,
      LocationSlice,
      LocationSliceDefaultPrimary,
      LocationSliceLocationPickupDropoffPrimary,
      LocationSliceVariation,
      LocationSliceDefault,
      LocationSliceLocationPickupDropoff,
      NavLinkSlice,
      NavLinkSliceDefaultPrimary,
      NavLinkSliceVariation,
      NavLinkSliceDefault,
      ParagraphSlice,
      ParagraphSliceDefaultPrimary,
      ParagraphSliceDefaultItem,
      ParagraphSliceVariation,
      ParagraphSliceDefault,
      StepsBlockSlice,
      StepsBlockSliceDefaultPrimary,
      StepsBlockSliceDefaultItem,
      StepsBlockSliceVariation,
      StepsBlockSliceDefault,
      TriptychSlice,
      TriptychSliceDefaultItem,
      TriptychSlicePromotedPrimary,
      TriptychSlicePromotedItem,
      TriptychSliceVariation,
      TriptychSliceDefault,
      TriptychSlicePromoted,
      WelcomeBannerSlice,
      WelcomeBannerSliceDefaultPrimary,
      WelcomeBannerSliceVariation,
      WelcomeBannerSliceDefault,
    };
  }
}
