// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  advertisement: dynamic(() => import("./Advertisement")),
  app_block: dynamic(() => import("./AppBlock")),
  curated_content: dynamic(() => import("./CuratedContent")),
  description: dynamic(() => import("./Description")),
  experience: dynamic(() => import("./Experience")),
  experience_search_block: dynamic(() => import("./ExperienceSearchBlock")),
  category_gallery: dynamic(() => import("./CategoryGallery")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  instagram: dynamic(() => import("./Instagram")),
  list: dynamic(() => import("./List")),
  location: dynamic(() => import("./Location")),
  nav_link: dynamic(() => import("./NavLink")),
  paragraph: dynamic(() => import("./Paragraph")),
  steps_block: dynamic(() => import("./StepsBlock")),
  triptych: dynamic(() => import("./Triptych")),
  welcome_banner: dynamic(() => import("./WelcomeBanner")),
};
